### PR TITLE
Support for MicroDVD format

### PR DESCRIPTION
**Pull request by stt**
Adds support for still somewhat popular https://en.wikipedia.org/wiki/MicroDVD format.

Still missing: control codes (colors, fonts) are not supported and are displayed as is.

### CODE REVIEW

**Comment by vladiibine** [comment]
Hi,
Thanks for the contribution! We'll look over your PR and it will most likely get integrated, because (at first glance) it doesn't change any existing functionality but just adds new stuff.

**Comment by stt** [comment]
Hi, yep only change to existing functionality was to expose the detection of the new format.
Though that's weird about the travis ci build failing. DFXPTestingMixIn is not removing the style-attributes like it was last time the tests were run, and they do pass locally. Version of beutifulsoup appears to be the same also.
Any idea what could be causing that?

**Comment by stt** [comment]
Oh, correction last master build was ran against beautifulsoup4 4.3.2 which was what I had locally, upgrading to 4.4.0 the same test broke locally.

**Comment by Iulia-Mada** [comment]
@stt I moved your commit in other PR( https://github.com/pbs/pycaption/pull/224 ) because there are a lot of changes in master and I can not rebase your branch. I am going to close this PR. Thanks!

**Pull request closed without merging**
