### PR TITLE
Python 3 support

### LINKED ISSUE #117: Python3 support
Would be great to have 3.3 and 3.4 python support. There's not many changes so I think that's doable.

### PR DESCRIPTION
**Pull request by sannies**
fixes #117

### CODE REVIEW

**Comment by vladiibine** [comment]
Hey, thanks for the awesome work. 
I'm checking it out, and the plan's like this:
I'll integrate tox, for testing on more versions of python. I'll also have to see what the BeautifulSoup instantiation does (you changed the 'xml' parameter to 'lxml-xml') > I have to see put some more tests with some more awkward samples, to see if those work as well.

After that, we'll integrate this.

Thanks again, for the effort and the patience :)

**Comment by avinassh** [comment]
Any update on this?

**Comment by sannies** [comment]
Is there anything that I can do to speed up the process?

**Comment by vladiibine** [comment]
If you want to set up tox for that project, that would help a lot.

**Comment by RobbieClarken** [comment]
I believe all that is required to set up tox for this project is to add a `tox.ini` file with:

```
[tox]
envlist = py27,py34,py35

[testenv]
commands = python setup.py test
```

You can then run the tests with the `tox` command (presuming you have installed tox with `pip install tox`). You will need python2.7, python3.4 and python3.5 binaries on your path. [pyenv](https://github.com/yyuu/pyenv) is a great tool for managing multiple versions. After setting it up according to the [installation instructions](https://github.com/yyuu/pyenv#installation) you can enable the required versions for this project with: `pyenv local 2.7.11 3.4.4 3.5.1`.

After doing all this I'm getting one failing test on 2.7:

```
======================================================================
FAIL: test_incorrectly_specified_positioning_is_explicitly_accepted (tests.test_dfxp_conversion.DFXPtoDFXPTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/robbie/Developer/Source/pycaption-sannies/tests/test_dfxp_conversion.py", line 122, in test_incorrectly_specified_positioning_is_explicitly_accepted
    SAMPLE_DFXP_INVALID_BUT_SUPPORTED_POSITIONING_OUTPUT)
AssertionError: u'<?xml version="1.0" encoding="utf-8"?>\n<tt xml:lang="en" xmlns="http://www.w3 [truncated]... != u'<?xml version="1.0" encoding="utf-8"?>\n<tt xml:lang="en" xmlns="http://www.w3 [truncated]...
Diff is 2691 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
```

**Comment by RobbieClarken** [comment]
It looks like the failed test is just due to the order of xml attributes differing from that the test expected:

```diff
     <p begin="00:00:05.700" end="00:00:06.210" region="r1" style="p" tts:displayAlign="after" tts:extent="30% 7.67%" tts:origin="20% 15.67%" tts:textAlign="center">
-     How are you?<span region="r2" tts:textAlign="center" tts:extent="30% 7.67%" tts:displayAlign="after" tts:origin="1px 2px">&gt;&gt;Fine, thx&lt;&lt;</span>
?                                                                                                         ---------------------
+     How are you?<span region="r2" tts:origin="1px 2px" tts:textAlign="center" tts:extent="30% 7.67%" tts:displayAlign="after">&gt;&gt;Fine, thx&lt;&lt;</span>
?                                  +++++++++++++++++++++
     </p>
     <p begin="00:00:07.900" end="00:00:08.900" region="r3" style="p" tts:displayAlign="before" tts:extent="60% 22%" tts:textAlign="right">
      Just fine?
     </p>
     <p begin="00:00:09.900" end="00:00:10.800" region="r4" style="p" tts:displayAlign="after" tts:origin="11% 11%" tts:textAlign="center">
-     <span tts:textAlign="right" region="r5" tts:textAlign="right" tts:displayAlign="after" tts:origin="11% 11%">&gt;&gt;&gt;Lol, yes!</span>
?                                                                                           ---------------------
+     <span tts:textAlign="right" region="r5" tts:origin="11% 11%" tts:textAlign="right" tts:displayAlign="after">&gt;&gt;&gt;Lol, yes!</span>
?                                            +++++++++++++++++++++
     </p>
```

Looking at the test code I see @sannies encountered this with Python 3:

```python
if six.PY2:
    self.assertEqual(result,
                 SAMPLE_DFXP_INVALID_BUT_SUPPORTED_POSITIONING_OUTPUT)
else:
    # attributes are sorted differently I guess testing for same length is close enough
    self.assertEqual(len(SAMPLE_DFXP_INVALID_BUT_SUPPORTED_POSITIONING_OUTPUT), len(result))
```


Seems the same thing can happen with Python 2 under certain conditions (it only happens when I test through tox for some reason).

**Comment by mtpain** [comment]
One more person here interested in seeing Python 3 supported, thanks!

**Comment by andreipradan** [comment]
This was merged here: #142 because this pr had some conflicts.

**Comment by andreipradan** [comment]
We encountered more compatibility issues and reverted this change.
Changes needed for python3 support will be included in a new version (1.0.0) that will be released very soon.
So pycaption < 1.0.0 will be python2 compatible, and >=1.0.0 will be python3 compatible.
Thank you!

**Comment by andreipradan** [comment]
In addition to @sannies PR (thank you!) we added these changes https://github.com/pbs/pycaption/commit/f73a033045c68c3fa03f2d3bdb1fbe5171cb783c and released pycaption 1.0.0

**Pull request merged**
