### PR TITLE
Add python3 compatibility.

### PR DESCRIPTION
**Pull request by virtosubogdan**
Made to look as much as possible to the master branch (version>1, python3 only)

### CODE REVIEW

**Comment by andreipradan** [comment]
ci shows 1 test failing, other than that, looks good

**Comment by bjester** [comment]
I have resolved the failing tests here, with explanation: https://github.com/pbs/pycaption/pull/186

**Comment by bjester** [comment]
I was able to upgrade `beautifulsoup4` as well, with tests passing in both python versions, shown here in [this commit](https://github.com/bjester/pycaption/commit/82225e1590cc5fb7b9993a306a04611a4a3a9f55). It's based off of `py27-py3-compat` so I would be happy to create a PR once this gets merged!

I was also able to refactor [this code](https://github.com/pbs/pycaption/blob/master/pycaption/dfxp/base.py#L400) to not generate the HTML manually, but use bs4. It's a fairly substantial refactor, so I stuck with the most straightforward solution in the above commit.

**Comment by virtosubogdan** [comment]
Thanks @bjester ! Nice work

**Pull request merged**
