### PR TITLE
Issue #59 Support offset time format in DFXP

### PR DESCRIPTION
**Pull request by rasod**

### CODE REVIEW

**Comment by vladiibine** [comment]
Thanks for the contribution. Could you also add some tests to this? 
Take a look at https://github.com/pbs/pycaption/blob/master/tests/test_dfxp.py#L17  for a more 'unit' type of test. Or take a look at https://github.com/pbs/pycaption/blob/master/tests/test_dfxp_conversion.py#L33  for more in the 'integration' category of tests.

If you only need dfxp-dfxp conversion, that's fine, you don't need to concern yourself with conversions to all the other formats (or even to dfxp), but please add at least a simple unit-ish test.

**Comment by rasod** [comment]
I added a test sample (SAMPLE_DFXP_TIME_FORMATS) that contains both time formats and updated the unit test (test_proper_timestamps) to test each type. I also added various conversion tests from DXFP to SAMI and SRT.

The test passed locally, not sure why build failed, says "Connection reset by peer" even before tests run. Did I do something wrong?

**Comment by vladiibine** [comment]
I don't think you did something wrong, but were just unlucky enough to have pypy disconnect the CI while the build was running. I'll try to get Travis to restart the build. Worst case scenario will be that we'll have to close and re-open the pull request (but that won't happen...most likely)

**Comment by rasod** [comment]
Closing
I'll wait for Issue #61 to be fixed before suggesting this change.

**Pull request closed without merging**
